name: Setup Vulkan SDK (Windows)
description: Downloads, caches, and configures the LunarG Vulkan SDK on the Windows runner.

inputs:
    version:
        description: Vulkan SDK version
        required: true

runs:
    using: composite

    steps:
        - name: Cache Vulkan SDK
          id: cache-vulkan
          uses: actions/cache@v4
          with:
            path: C:\VulkanSDK\${{ inputs.version }}
            key: vulkan-sdk-windows-${{ inputs.version }}-${{ github.ref }}
            restore-keys: |
              vulkan-sdk-windows-${{ inputs.version }}-refs/heads/main
              vulkan-sdk-windows-${{ inputs.version }}-

        - name: Download and install Vulkan SDK
          if: steps.cache-vulkan.outputs.cache-hit != 'true'
          shell: pwsh
          run: |
            Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ inputs.version }}/windows/vulkansdk-windows-X64-${{ inputs.version }}.exe" -OutFile VulkanSDK-Installer.exe
            Start-Process -FilePath .\VulkanSDK-Installer.exe -ArgumentList "--accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.volk" -Wait
            Remove-Item VulkanSDK-Installer.exe

        - name: Setup environment
          shell: pwsh
          run: |
            echo "VULKAN_SDK=C:\VulkanSDK\${{ inputs.version }}" >> $env:GITHUB_ENV
            echo "C:\VulkanSDK\${{ inputs.version }}\Bin" >> $env:GITHUB_PATH
